export const env:string="production"
export const url=["http://localhost:8000/account","http://api.fishstar.xyz/account"]
export const PathLogin="/login"
export const PathRegister="/register"
export const PathAllUser="/allUser"
export const PathAllApp="/allApp"
export const PathAddApp="/addApp"
export const PathAddUser="/addUser"
export const getPathLogin=()=>`${url[env==="debug"?0:1]}${PathLogin}`
export const getPathRegister=()=>`${url[env==="debug"?0:1]}${PathRegister}`
export const getPathAllUser=()=>`${url[env==="debug"?0:1]}${PathAllUser}`
export const getPathAllApp=()=>`${url[env==="debug"?0:1]}${PathAllApp}`
export const getPathAddApp=()=>`${url[env==="debug"?0:1]}${PathAddApp}`
export const getPathAddUser=()=>`${url[env==="debug"?0:1]}${PathAddUser}`